services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend  
    environment:
      PORT: 3333
    ports:
      - '3333:3333'
    restart: "no"
    volumes:
      - ./backend/src:/app/src
  koa:
    build:
      context: ./koa
      dockerfile: Dockerfile.dev
    container_name: koa
    environment:
      PORT: 5555
    ports:
      - '5555:5555'
    restart: "no"
    volumes:
      - ./koa/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      PORT: 5173
    ports:
      - '5173:5173'
    restart: "no"
    volumes:
      - ./frontend/src:/app/src