services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend 
    depends_on:
      - redis 
    environment:
      PORT: 3333
    ports:
      - '3333:3333'
    restart: "no"
    volumes:
      - ./backend/src:/app/src
  koa:
    build:
      context: ./koa
      dockerfile: Dockerfile.dev
    container_name: koa
    environment:
      PORT: 5555
    ports:
      - '5555:5555'
    restart: "no"
    volumes:
      - ./koa/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      PORT: 5173

    ports:
      - '5173:5173'
    restart: "no"
    volumes:
      - ./frontend/src:/app/src

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      PORT: 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  redis_data:
